name: Bump version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        CUSTOM_TAG: 'custom txt'
        
        
    - uses: actions/checkout@v3
    - name: Create a Release
      uses: elgohr/Github-Release-Action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: MyReleaseMessage
      
    - uses: actions/setup-java@v3
      with:
          java-version: '11'
          distribution: 'adopt'
    - name: Maven setup    
      run: mvn -f pom.xml
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   
   
